# Generated by Django 2.2.2 on 2019-11-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('in_office', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_time', models.DateTimeField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotproject1.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='ApptRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotproject1.Professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotproject1.Student')),
            ],
        ),
    ]
